arduino/ArduinoCore-zephyr

cores/arduino/Arduino.h
cores/arduino/time_macros.h

Fixes compilation error found at https://www.cnx-software.com/2024/12/10/arduino-core-for-zephyr-beta-released/

core: add time related macros

---

libraries/Wire/Wire.cpp
loader/llext_exports.c

Implemented I2C setClock funtion.  
```
void arduino::ZephyrI2C::setClock(uint32_t freq) {
uint8_t speed = 	I2C_SPEED_STANDARD;
if(freq >  0x06u ) {
if(freq == 100000) {
speed = I2C_SPEED_STANDARD;
} else if(freq == 400000) {
speed = I2C_SPEED_FAST;
} else if(freq == 1000000) {
speed = I2C_SPEED_FAST_PLUS;
} else {
speed = I2C_SPEED_STANDARD;
}
} else {
speed = (uint8_t) freq;
}
uint32_t i2c_cfg = I2C_MODE_CONTROLLER |
I2C_SPEED_SET(speed);
if (i2c_configure(i2c_dev, i2c_cfg)) {
//Serial.println("Failed to configure i2c interface.");
}
}
```
frequency can be 100000, 400000 or I2C_SPEED_STANDARD or I2C_SPEED_FAST, while I2C_SPEED_FAST_PLUS is there (like in mbed) does not seem to register right now so only 100khz and 400khz are supported.
See …

Implement SetClock Function

---

cores/arduino/zephyrCommon.cpp

Fixes #25 
It was getting the 32 bit value dividing by system clock speed and returning it, so it never fully went through the 32 bit value to properly rollover changed to retrieve the 64 bit value instead, which appears to work
```
unsigned long micros(void) {
return k_cyc_to_us_floor32(k_cycle_get_64());
}
```
Output from example sketch from before, shows rollover now:
```
US: 4288826633 4289826702 1000069	MS: 4288826 4289826 1000
US: 4289826733 4290826802 1000069	MS: 4289826 4290826 1000
US: 4290826833 4291826902 1000069	MS: 4290826 4291826 1000
US: 4291826933 4292827002 1000069	MS: 4291826 4292827 1001
US: 4292827057 4293827102 1000045	MS: 4292827 4293827 1000
US: 4293827133 4294827202 1000069	MS: 4293827 4294827 1000
US: 4294827233 860006 1000069	MS: 4294827 4295827 1000
US: 860058 …
```

Fix micros() rollover

---

cores/arduino/Arduino.h
cores/arduino/zephyrCommon.cpp
loader/boards/arduino_giga_r1_m7.overlay

resolves #36 
The current released version was always reading with 12 bits of resolution. The Arduino analogRead web page said that by default it should default to 10 bits.
The updated code is now ignoring the arduino_adc[idx].resolution field as this is setup for 12 and you can not change it run time.
Like the MBED version,  this version is using the static variable read_resolution to hold the current resolution.  Which we then pass through to zephyr when we do the reads.
I also changed the parameter buf that we pass through to zephyr from in16_t to uint16_t as if you choose resolution of 16 bits it was returning negative values.

Implement analogReadResolution

---

cores/arduino/CMakeLists.txt
cores/arduino/main.cpp
cores/arduino/threads.cpp
loader/llext_exports.c
variants/llext/linker_script.ld

@KurtE - @facchinm 
Changes made to:
llext_exports.c
main.cpp in core arduino directory
linker_script.ld
Details of changes are shown in https://github.com/arduino/ArduinoCore-zephyr/issues/37
Test sketches if you want to try:
[thread_test_sketches.zip](https://github.com/user-attachments/files/18519157/thread_test_sketches.zip)
EDIT: Just tried building for nano 33 sense ble and getting error
```
/home/zephyr-sdk-0.16.8/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: app/libapp.a(llext_exports.c.obj):(._llext_const_symbol.static.__llext_sym___cxa_pure_virtual_+0x4): undefined reference to `__cxa_pure_virtual'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
FATAL ERROR: command exited with status 1: …
```

update to get threads working

---

variants/arduino_nano_33_ble/variant.h
variants/arduino_nano_33_ble_sense/variant.h
variants/arduino_nano_33_iot/variant.h

While playing with SDfat kept getting an error about ss pin not defined.  Then @KurtE reminded that on the teensy they are defined in the core.  Then remembered say that for the giga.  When I looked for the nano boards (variant.h) they were not covered.  This PR adds:
```
// TODO: correctly handle these legacy defines
#define MOSI    0
#define MISO    0
#define SCK     0
#define SS      0
#define SDA     0
#define SCL     0
```
to the nano variant.h files (ble, sense and iot).  
recompiled core and retested and the sdfat compile error disappeared.

Added legacy pin coverager for nano boards

---

cores/arduino/zephyrCommon.cpp

Fixes #60 
The rollover fix for the giga used the 64 bit timer instead of 32 bits.  The nano does not have a 64 bit timer, so you need to use the 32 bit instead.
So I know check to see if the processor supports 64 bits if so use it else fall back to 32 bit.
@mjs513 you might want to try this out to see if it fixes the issue for you

Fix micros() for nano without breaking giga

---

loader/boards/arduino_giga_r1_m7.overlay

resolves: [#64](https://github.com/arduino/ArduinoCore-zephyr/issues/64)
Removed the pins logical Arduino pins 11-13 from the PWM pin list, plus their defines
for the timers.
With these defines in place, the pins Alternate Function settings were set to that of the timers
versus the SPI value (5)
Note: This was done by [@mjs513](https://github.com/mjs513) and myself.

GIGA: Remove Arduino pins 11-13 from PWM list to fix SPI1

---

cores/arduino/main.cpp
loader/boards/arduino_nano_33_ble_sense.overlay
variants/arduino_nano_33_ble_sense/variant.cpp

Resolves: #51
There is an IO pin on the NANO that that when turned on, enables most of the sensors on the BLE sense which are on SPI1.   The MBED version, enables this pin as part of the main().
Which I am trying to emulate.  There is code already in, that if you use at least one of the zephyr device drivers, will eanble this pin.  However that does not help when you are using external libraries or the like.
So I added details about this pin in our overlay file, in the zephyr,user section.
I then added code to main.cpp, that is only included if your are building using an NRFX board.  Currently the nano and one of the nicla boards.  Could also specically only do this on the NANO, but probably does not matter as, the code tries to find that property and only if it is found, does it turn on …

Nano 33 BLE - enable the SPI1 sensors

---

loader/llext_exports.c

Added atan2 to llext_exports.c to resolve issues with the BMI270 api that I have seen on the Nano and Giga.  Probably for all boards that use the BMI270.
See issue:
[Portenta H7 Lite: Std lib atan2 causes a Undefined in Symbol Table #73](https://github.com/arduino/ArduinoCore-zephyr/issues/73)
[Nano 33 and Giga: BMI270/BMM150 Compiles but Looses Com Port after Upload #69](https://github.com/arduino/ArduinoCore-zephyr/issues/69)
Didn't rebuild for this PR figured workflow.  If you want I can.  Been just updating firmware and variants for this change.  Unfortunately I have already incorporated @KurtE's changes for the H7

update to llext_exports.c

---

.github/workflows/build.yml
.github/workflows/package_core.yml
extra/bootstrap.sh
extra/build.sh
extra/build_all.sh
extra/gen_package_index_json.sh
extra/get_variant_name.sh
extra/package.sh
extra/targets.json
extra/zephyr-core-template.json

This PR updates the CI infrastructure to add full variant coverage to the testing stage, and archive the build results to long-term storage.

Github Actions: build and release workflow

---

.github/workflows/package_core.yml
README.md
extra/bootstrap.sh
extra/build.sh
extra/package_tool.sh
extra/sync-zephyr-artifacts/README.md
extra/zephyr-sketch-tool/README.md

* Make `bootstrap.sh` install the Zephyr SDK automatically
* Make `build.sh` take at least one argument, print list of targets if no argument or `-h`/`--help` given
* Document these changes in the `README.md` of the repo

bootstrap / build.sh cleanups

---

.github/workflows/package_core.yml
boards.txt
extra/build.sh
loader/llext_exports.c
variants/arduino_giga_r1_stm32h747xx_m7/arduino_giga_r1_stm32h747xx_m7.overlay
variants/arduino_portenta_h7_stm32h747xx_m7/arduino_portenta_h7_stm32h747xx_m7.overlay
variants/frdm_rw612_rw612/frdm_rw612_rw612.overlay
west.yml

- fix `build.sh` requiring Python env or `ZEPHYR_SDK_INSTALL_DIR`
- fix `readelf` not being found in CI
- add missing `cmsis_6` submodule
- fix DCMI overlays
- fix merged shield name

zephyr: update to zephyr-arduino-20250520

---

cores/arduino/SerialUSB.h
cores/arduino/USB.cpp

Should resolve #35 
Tested with Portenta, but should work on all of the others as well.
Current code would hang after a few Serial.print like statements happened when we are not connected to the Serial monitor.
So I put overrides in for the Serial.write(buf, cnt) and Serial.flush() That would first check to see if Serial returns true (DTR)...
This appears to match the behavior of the MBED Portenta H8 code.

If sketch is not connected to serial - dump serial output

---

variants/arduino_giga_r1_stm32h747xx_m7/pure_analog_pins.h
variants/arduino_portenta_h7_stm32h747xx_m7/pure_analog_pins.h

Both GIGA and Portenta H7 have the files pure_analog_pins.h which is included within Arduino.h
If you should by chance have a .c file either in library or sketch that include Arduino.h such as simple file:
foo.c
```
#include <Arduino.h>
void foo() {
}
```
The build will fail with errors like:
```
In file included from C:\Users\kurte\Documents\Arduino\hardware\arduino-git\ArduinoCore-zephyr\variants\arduino_portenta_h7_stm32h747xx_m7/variant.h:6,
from C:\Users\kurte\Documents\Arduino\hardware\arduino-git\ArduinoCore-zephyr\cores\arduino/Arduino.h:133,
from C:\Users\kurte\AppData\Local\Temp\.arduinoIDE-unsaved2025512-1916-i38ngk.ik13\sketch_jun12a\foo.c:1:
C:\Users\kurte\Documents\Arduino\hardware\arduino-git\ArduinoCore-zephyr\variants\arduino_portenta_h7_stm32h747xx_m7/pure_analog_pins.h:2 …
```

Fix .c file compile that include <Arduino.h>

---

variants/arduino_portenta_h7_stm32h747xx_m7/arduino_portenta_h7_stm32h747xx_m7.overlay

There was an issue, where I think I screwed up earlier and defined the pins as all GPIO_ACTIVE_LOW in the digital-pin-gpios.
With this the digitalWrites were inverted.
I was having an issue with my ILI9341 library where the CS and DC pins states were inverted.
Created simple example sketch:
```
void setup() {
// put your setup code here, to run once:
pinMode(2, OUTPUT);
pinMode(3, OUTPUT);
pinMode(4, OUTPUT);
}
void loop() {
// put your main code here, to run repeatedly:
digitalWrite(2, HIGH);
digitalWrite(3, HIGH);
digitalWrite(4, HIGH);
delay(50);
digitalWrite(2, LOW);
digitalWrite(3, LOW);
digitalWrite(4, LOW);
delay(250);
}
```
Before these changes:
With these changes:
And simple ILI9341 driver I have for Zephyr is working again... (Was working on GIGA)

Portenta H7: Fix digital-pin-gpios - problem with digitalWrite

---

cores/arduino/SerialUSB.h

This would have been spotted if we extend the CI to compile all the examples (TestClient in particular).

SerialUSB: fix missing overload after #123

---

libraries/SocketWrapper/SocketHelpers.h

[github.com/zephyrproject-rtos/zephyr/pull/89048 ](http://github.com/zephyrproject-rtos/zephyr/pull/89048)

fixing net_mgmt event handler callback signature after zephyr #89048

---

boards.txt

Completes https://github.com/arduino/ArduinoCore-zephyr/commit/c89521ccb9fe94075c3102dc15e40dc24d10d594 for all the boards

Restore Debug menu functionality

---

variants/arduino_opta_stm32h747xx_m7/arduino_opta_stm32h747xx_m7.overlay

Assign pb6(scl) and pb7(sda) to i2c1

opta: fix i2c1 pins conflicting with BLE hci

---

loader/fixups.c
loader/llext_exports.c

Add a callback function for the touch device
within the fixups for the GIGA. This callback
simply remembers the last touch that happened and
sets a semaphore.
There is also a function added to retrieve this data.
Needed to add the callback function into the exports file.
EDIT: As I mentioned in
https://github.com/arduino/ArduinoCore-zephyr/issues/92
This is maybe not a complete setup yet. Currently the zephyr touch device is configured for only one touch
Where it believe is supposed to support up to 5. Also with it only doing one touch, it does not support
gestures. I will integrate our WIP touch code into the Arduino_GIGATouch library such that it is all
available for us or others to fill this in.
This is a replacement for #134 
... 
See that one for more details, like, I have an open PR …

Add support for receiving input callback in sketches. 

---

.github/workflows/format_check.yml
.github/workflows/package_core.yml

The Github UI for required checks does not integrate with the workflows described in the .github directory. Currently jobs that are never started due to conditional execution are not even reported, so the UI shows "expected" and locks up merges.
Collect format errors so that the Github UI can be happy to track one job that is always executed. This job will fail if any of the format-check jobs failed or were cancelled, and will be ignored (but reported) otherwise.

format-check: add collect errors job

---

.github/workflows/format_check.yml

When multiple files change, tj-action/changed-files separates file names with a space, so the output is ambiguous. Switch to JSON output and use jq to convert the array to a text file with one file name per line, a format that is readily usable for clang-format-action.

format_check: fix it again

---

.github/workflows/build.yml

The current `ci` Docker image is too large for the basic Github runner. Switch to `ci-base` and manually run `action-zephyr-setup` reduces the image size and makes it run again.

ci: replace Docker image
